---
- name: test if memcached_port is set correctly
  assert:
    that:
      - memcached_port is defined
      - memcached_port | int
      - memcached_port | int > 0
      - memcached_port | int < 65536

- name: test if memcached_listenon is set correctly
  assert:
    that:
      - memcached_listenon is defined
      - memcached_listenon | length > 0

- name: test if memcached_maxconn is set correctly
  assert:
    that:
      - memcached_maxconn is defined
      - memcached_maxconn | int
      - memcached_maxconn | int >= 1

- name: test if memcached_cachesize is set correctly
  assert:
    that:
      - memcached_cachesize is defined
      - memcached_cachesize | int
      - memcached_cachesize | int >= 1
