---
# tasks file for memcached
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: memcached
    state: present

- name: allow software to be configured
  copy:
    src: memcached.service
    dest: /usr/lib/systemd/system/memcached.service
  when:
    - ansible_distribution == "Archlinux"
  notify:
    - systemctl daemon-reload

- name: flush handlers
  meta: flush_handlers

- name: configure software
  template:
    src: "{{ ansible_distribution }}-memcached.j2"
    dest: "{{ memcached_configfile }}"
  notify:
    - restart software

- name: start software
  service:
    name: memcached
    state: started
  when:
    - ansible_virtualization_type != "docker"
