---
# tasks file for memcached

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install memcached
  package:
    name: memcached
    state: present

- name: allow memcached to be configured
  copy:
    src: memcached.service
    dest: /usr/lib/systemd/system/memcached.service
    mode: "0644"
  when:
    - ansible_distribution == "Archlinux"
  notify:
    - systemctl daemon-reload

- name: flush handlers
  meta: flush_handlers

- name: configure memcached
  template:
    src: "{{ ansible_distribution }}-memcached.j2"
    dest: "{{ memcached_configfile }}"
    mode: "0644"
  notify:
    - restart memcached

- name: start memcached
  service:
    name: memcached
    state: started
