---
# tasks file for memcached
- name: install memcached
  package:
    name: memcached
    state: present
  register: memcached_install_memcached
  until: memcached_install_memcached is succeeded
  retries: 3

- name: allow memcached to be configured
  copy:
    src: memcached.service
    dest: /usr/lib/systemd/system/memcached.service
  when:
    - ansible_distribution == "Archlinux"
  notify:
    - systemctl daemon-reload

- name: flush handlers
  meta: flush_handlers

- name: configure memcached
  template:
    src: "{{ ansible_distribution }}-memcached.j2"
    dest: "{{ memcached_configfile }}"
  notify:
    - restart memcached

- name: start memcached
  service:
    name: memcached
    state: started
  when:
    - ansible_virtualization_type != "docker"
