---
# handlers file for memcached

- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes
  notify:
    - restart software

- name: Restart memcached
  ansible.builtin.service:
    name: memcached
    state: restarted
  when:
    - not ansible_check_mode
