---
# handlers file for memcached

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  notify:
    - restart software

- name: restart memcached
  service:
    name: memcached
    state: restarted
  when:
    - not ansible_check_mode | bool
