---
# handlers file for memcached
- name: restart software
  service:
    name: memcached
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  notify:
    - restart software
